-- MySQL dump generated by scripts/backup_mysql.py
-- Database: fast_admin

CREATE DATABASE IF NOT EXISTS `fast_admin`;
USE `fast_admin`;

SET FOREIGN_KEY_CHECKS=0;

--
-- Table structure for table `QRTZ_BLOB_TRIGGERS`
--

DROP TABLE IF EXISTS `QRTZ_BLOB_TRIGGERS`;
CREATE TABLE `QRTZ_BLOB_TRIGGERS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `TRIGGER_NAME` varchar(190) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  `BLOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  KEY `SCHED_NAME` (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `QRTZ_BLOB_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_BLOB_TRIGGERS`
--


--
-- Table structure for table `QRTZ_CALENDARS`
--

DROP TABLE IF EXISTS `QRTZ_CALENDARS`;
CREATE TABLE `QRTZ_CALENDARS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `CALENDAR_NAME` varchar(190) NOT NULL,
  `CALENDAR` blob NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`CALENDAR_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_CALENDARS`
--


--
-- Table structure for table `QRTZ_CRON_TRIGGERS`
--

DROP TABLE IF EXISTS `QRTZ_CRON_TRIGGERS`;
CREATE TABLE `QRTZ_CRON_TRIGGERS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `TRIGGER_NAME` varchar(190) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  `CRON_EXPRESSION` varchar(120) NOT NULL,
  `TIME_ZONE_ID` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `QRTZ_CRON_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_CRON_TRIGGERS`
--


--
-- Table structure for table `QRTZ_FIRED_TRIGGERS`
--

DROP TABLE IF EXISTS `QRTZ_FIRED_TRIGGERS`;
CREATE TABLE `QRTZ_FIRED_TRIGGERS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `ENTRY_ID` varchar(95) NOT NULL,
  `TRIGGER_NAME` varchar(190) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  `INSTANCE_NAME` varchar(190) NOT NULL,
  `FIRED_TIME` bigint(20) NOT NULL,
  `SCHED_TIME` bigint(20) NOT NULL,
  `PRIORITY` int(11) NOT NULL,
  `STATE` varchar(16) NOT NULL,
  `JOB_NAME` varchar(190) DEFAULT NULL,
  `JOB_GROUP` varchar(190) DEFAULT NULL,
  `IS_NONCONCURRENT` varchar(1) DEFAULT NULL,
  `REQUESTS_RECOVERY` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`,`ENTRY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_FIRED_TRIGGERS`
--


--
-- Table structure for table `QRTZ_JOB_DETAILS`
--

DROP TABLE IF EXISTS `QRTZ_JOB_DETAILS`;
CREATE TABLE `QRTZ_JOB_DETAILS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `JOB_NAME` varchar(190) NOT NULL,
  `JOB_GROUP` varchar(190) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `JOB_CLASS_NAME` varchar(250) NOT NULL,
  `IS_DURABLE` varchar(1) NOT NULL,
  `IS_NONCONCURRENT` varchar(1) NOT NULL,
  `IS_UPDATE_DATA` varchar(1) NOT NULL,
  `REQUESTS_RECOVERY` varchar(1) NOT NULL,
  `JOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`JOB_NAME`,`JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_JOB_DETAILS`
--


--
-- Table structure for table `QRTZ_LOCKS`
--

DROP TABLE IF EXISTS `QRTZ_LOCKS`;
CREATE TABLE `QRTZ_LOCKS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `LOCK_NAME` varchar(40) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`LOCK_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_LOCKS`
--

INSERT INTO `QRTZ_LOCKS` (`SCHED_NAME`, `LOCK_NAME`) VALUES ('FastApplicationScheduler', 'TRIGGER_ACCESS');

--
-- Table structure for table `QRTZ_PAUSED_TRIGGER_GRPS`
--

DROP TABLE IF EXISTS `QRTZ_PAUSED_TRIGGER_GRPS`;
CREATE TABLE `QRTZ_PAUSED_TRIGGER_GRPS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_PAUSED_TRIGGER_GRPS`
--


--
-- Table structure for table `QRTZ_SCHEDULER_STATE`
--

DROP TABLE IF EXISTS `QRTZ_SCHEDULER_STATE`;
CREATE TABLE `QRTZ_SCHEDULER_STATE` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `INSTANCE_NAME` varchar(190) NOT NULL,
  `LAST_CHECKIN_TIME` bigint(20) NOT NULL,
  `CHECKIN_INTERVAL` bigint(20) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`INSTANCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_SCHEDULER_STATE`
--


--
-- Table structure for table `QRTZ_SIMPLE_TRIGGERS`
--

DROP TABLE IF EXISTS `QRTZ_SIMPLE_TRIGGERS`;
CREATE TABLE `QRTZ_SIMPLE_TRIGGERS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `TRIGGER_NAME` varchar(190) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  `REPEAT_COUNT` bigint(20) NOT NULL,
  `REPEAT_INTERVAL` bigint(20) NOT NULL,
  `TIMES_TRIGGERED` bigint(20) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `QRTZ_SIMPLE_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_SIMPLE_TRIGGERS`
--


--
-- Table structure for table `QRTZ_SIMPROP_TRIGGERS`
--

DROP TABLE IF EXISTS `QRTZ_SIMPROP_TRIGGERS`;
CREATE TABLE `QRTZ_SIMPROP_TRIGGERS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `TRIGGER_NAME` varchar(190) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  `STR_PROP_1` varchar(512) DEFAULT NULL,
  `STR_PROP_2` varchar(512) DEFAULT NULL,
  `STR_PROP_3` varchar(512) DEFAULT NULL,
  `INT_PROP_1` int(11) DEFAULT NULL,
  `INT_PROP_2` int(11) DEFAULT NULL,
  `LONG_PROP_1` bigint(20) DEFAULT NULL,
  `LONG_PROP_2` bigint(20) DEFAULT NULL,
  `DEC_PROP_1` decimal(13,4) DEFAULT NULL,
  `DEC_PROP_2` decimal(13,4) DEFAULT NULL,
  `BOOL_PROP_1` varchar(1) DEFAULT NULL,
  `BOOL_PROP_2` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  CONSTRAINT `QRTZ_SIMPROP_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_SIMPROP_TRIGGERS`
--


--
-- Table structure for table `QRTZ_TRIGGERS`
--

DROP TABLE IF EXISTS `QRTZ_TRIGGERS`;
CREATE TABLE `QRTZ_TRIGGERS` (
  `SCHED_NAME` varchar(120) NOT NULL,
  `TRIGGER_NAME` varchar(190) NOT NULL,
  `TRIGGER_GROUP` varchar(190) NOT NULL,
  `JOB_NAME` varchar(190) NOT NULL,
  `JOB_GROUP` varchar(190) NOT NULL,
  `DESCRIPTION` varchar(250) DEFAULT NULL,
  `NEXT_FIRE_TIME` bigint(20) DEFAULT NULL,
  `PREV_FIRE_TIME` bigint(20) DEFAULT NULL,
  `PRIORITY` int(11) DEFAULT NULL,
  `TRIGGER_STATE` varchar(16) NOT NULL,
  `TRIGGER_TYPE` varchar(8) NOT NULL,
  `START_TIME` bigint(20) NOT NULL,
  `END_TIME` bigint(20) DEFAULT NULL,
  `CALENDAR_NAME` varchar(190) DEFAULT NULL,
  `MISFIRE_INSTR` smallint(6) DEFAULT NULL,
  `JOB_DATA` blob,
  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),
  KEY `SCHED_NAME` (`SCHED_NAME`,`JOB_NAME`,`JOB_GROUP`),
  CONSTRAINT `QRTZ_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) REFERENCES `QRTZ_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Data for table `QRTZ_TRIGGERS`
--


--
-- Table structure for table `sys_config`
--

DROP TABLE IF EXISTS `sys_config`;
CREATE TABLE `sys_config` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `config_name` varchar(128) NOT NULL COMMENT '参数名称',
  `config_key` varchar(128) NOT NULL COMMENT '参数键名',
  `config_value` varchar(1024) DEFAULT NULL COMMENT '参数键值',
  `config_type` tinyint(1) DEFAULT '0' COMMENT '是否系统内置：1是 0否',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` varchar(64) DEFAULT NULL,
  `created_id` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `updated_id` varchar(32) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_key` (`config_key`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统参数';

--
-- Data for table `sys_config`
--


--
-- Table structure for table `sys_dept`
--

DROP TABLE IF EXISTS `sys_dept`;
CREATE TABLE `sys_dept` (
  `id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID（KSUID）',
  `name` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '部门名称',
  `pid` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '上级部门ID',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态：1-启用，0-禁用',
  `remark` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否启用',
  `created_by` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `updated_by` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记：false未删除，true已删除',
  `created_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `updated_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  KEY `idx_pid` (`pid`),
  KEY `idx_status` (`status`),
  KEY `idx_is_enabled` (`is_enabled`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统-部门表';

--
-- Data for table `sys_dept`
--

INSERT INTO `sys_dept` (`id`, `name`, `pid`, `status`, `remark`, `is_enabled`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35SYbLjJaBxhMOAl7LdELC3Zezi', '雨轩科技', NULL, 1, NULL, 1, 'Sir丶雨轩', '2025-11-14 15:23:29.366000', 'Sir丶雨轩', '2025-11-14 15:36:52.468000', 0, '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh');
INSERT INTO `sys_dept` (`id`, `name`, `pid`, `status`, `remark`, `is_enabled`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35SZAmUMGKqvpWTC2EQODUKm59T', '研发部门', '35SYbLjJaBxhMOAl7LdELC3Zezi', 1, NULL, 1, 'Sir丶雨轩', '2025-11-14 15:28:11.661000', 'Sir丶雨轩', '2025-11-14 15:28:11.684000', 0, '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh');
INSERT INTO `sys_dept` (`id`, `name`, `pid`, `status`, `remark`, `is_enabled`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35SZBmqUlmbghCPu2cyeSgv8GCo', '测试部门', '35SYbLjJaBxhMOAl7LdELC3Zezi', 1, NULL, 1, 'Sir丶雨轩', '2025-11-14 15:28:19.009000', 'Sir丶雨轩', '2025-11-14 15:28:19.012000', 0, '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh');
INSERT INTO `sys_dept` (`id`, `name`, `pid`, `status`, `remark`, `is_enabled`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35SZCuQonf4kzmioV1almTAYpY7', '研发一部', '35SZAmUMGKqvpWTC2EQODUKm59T', 1, NULL, 1, 'Sir丶雨轩', '2025-11-14 15:28:28.891000', 'Sir丶雨轩', '2025-11-14 15:28:28.893000', 0, '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh');

--
-- Table structure for table `sys_dict_data`
--

DROP TABLE IF EXISTS `sys_dict_data`;
CREATE TABLE `sys_dict_data` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `dict_type` varchar(128) NOT NULL COMMENT '字典类型',
  `dict_label` varchar(128) NOT NULL COMMENT '字典标签',
  `dict_value` varchar(128) NOT NULL COMMENT '字典键值',
  `dict_sort` int(11) DEFAULT '0' COMMENT '排序',
  `css_class` varchar(64) DEFAULT NULL COMMENT '样式属性（颜色等）',
  `list_class` varchar(64) DEFAULT NULL COMMENT '表格回显样式（如 success/danger）',
  `is_default` tinyint(1) DEFAULT '0' COMMENT '是否默认：1是 0否',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：1启用 0禁用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` varchar(64) DEFAULT NULL,
  `created_id` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `updated_id` varchar(32) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_dict_type` (`dict_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典数据';

--
-- Data for table `sys_dict_data`
--


--
-- Table structure for table `sys_dict_type`
--

DROP TABLE IF EXISTS `sys_dict_type`;
CREATE TABLE `sys_dict_type` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `dict_name` varchar(128) NOT NULL COMMENT '字典名称',
  `dict_type` varchar(128) NOT NULL COMMENT '字典类型（编码）',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：1启用 0禁用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` varchar(64) DEFAULT NULL,
  `created_id` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `updated_id` varchar(32) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_dict_type` (`dict_type`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='字典类型';

--
-- Data for table `sys_dict_type`
--


--
-- Table structure for table `sys_file`
--

DROP TABLE IF EXISTS `sys_file`;
CREATE TABLE `sys_file` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `original_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `storage_key` varchar(512) NOT NULL COMMENT '存储相对路径/objectKey',
  `url` varchar(1024) NOT NULL COMMENT '上传时算好的完整访问地址',
  `size` bigint(20) NOT NULL COMMENT '文件字节数',
  `content_type` varchar(128) DEFAULT NULL,
  `ext` varchar(16) DEFAULT NULL,
  `hash` varchar(64) DEFAULT NULL COMMENT 'sha256',
  `storage_type` varchar(16) NOT NULL COMMENT '上传时使用的存储类型',
  `config_id` varchar(32) NOT NULL COMMENT '上传时使用的配置 id',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` varchar(64) DEFAULT NULL COMMENT '业务 id',
  `created_by` varchar(64) DEFAULT NULL,
  `created_id` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `updated_id` varchar(32) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_file_biz` (`biz_type`,`biz_id`),
  KEY `idx_file_hash` (`hash`),
  KEY `idx_file_config` (`config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件记录';

--
-- Data for table `sys_file`
--

INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DlTPKAfIIGGMnDBvR0Ai3HzE2E', '3bdee3411a3744ee67c241854b7ca2.jpg', 'fast-admin/2026/05/15/3DlTP8JjUDLcNzPyq3Hdmy8JlnK.jpg', 'https://oss.yuxuan66.com/fast-admin/2026/05/15/3DlTP8JjUDLcNzPyq3Hdmy8JlnK.jpg', 43477, 'image/jpeg', 'jpg', '0a49c21c3391dde9deedb8a7b1fd70bc55203f8d35e9ce755644053d5955c8fd', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', NULL, NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:33:50', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:34:27', 1);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DlTW6UKj4lSpyg6br9CsvjZor5', '3bdee3411a3744ee67c241854b7ca2.jpg', 'fast-admin/2026/05/15/3DlTW665QAD26NOFhC0SJ4YgISo.jpg', 'https://oss.yuxuan66.com/fast-admin/2026/05/15/3DlTW665QAD26NOFhC0SJ4YgISo.jpg', 43477, 'image/jpeg', 'jpg', '0a49c21c3391dde9deedb8a7b1fd70bc55203f8d35e9ce755644053d5955c8fd', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', NULL, NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:34:44', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:35:22', 1);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DlTXhOGTSQplWTzohX5D99CkMp', '3bdee3411a3744ee67c241854b7ca2.jpg', 'fast-admin/2026/05/15/3DlTXed2QezXyAZ5Urwr4JHFlOr.jpg', 'https://oss.yuxuan66.com/fast-admin/2026/05/15/3DlTXed2QezXyAZ5Urwr4JHFlOr.jpg', 43477, 'image/jpeg', 'jpg', '0a49c21c3391dde9deedb8a7b1fd70bc55203f8d35e9ce755644053d5955c8fd', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', NULL, NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:34:58', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:35:15', 1);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DmhLAkBilQ8BcSa4Fh1VSnbaSK', '3bdee3411a3744ee67c241854b7ca2.jpg', 'fast-admin/2026/05/16/3DmhKy1aq4Gm95BzapkP0TFVIj7.jpg', 'https://oss.yuxuan66.com/fast-admin/2026/05/16/3DmhKy1aq4Gm95BzapkP0TFVIj7.jpg', 43477, 'image/jpeg', 'jpg', '0a49c21c3391dde9deedb8a7b1fd70bc55203f8d35e9ce755644053d5955c8fd', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', NULL, NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 08:58:13', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 08:58:13', 0);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DmhrgSOCOzyyzt3X0vM6neEcKS', '20260508_02.rar', 'fast-admin/2026/05/16/3DmhiBEdHuAChqCvLUJe4VqbBXc.rar', 'https://oss.yuxuan66.com/fast-admin/2026/05/16/3DmhiBEdHuAChqCvLUJe4VqbBXc.rar', 888480473, 'application/x-rar', 'rar', '93d74d1a42fd3ceb24bfbd17d46c5e9bd11bca320983ed82516a240248b48146', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', NULL, NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:02:33', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:02:33', 0);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DmjuAQ4oMmKvjlnR1cRitt2ARF', '3bdee3411a3744ee67c241854b7ca2.jpg', 'fast-admin/2026/05/16/3Dmju1b4qO0arqAFkwLF86mtl9q.jpg', 'https://oss.yuxuan66.com/fast-admin/2026/05/16/3Dmju1b4qO0arqAFkwLF86mtl9q.jpg', 43477, 'image/jpeg', 'jpg', '0a49c21c3391dde9deedb8a7b1fd70bc55203f8d35e9ce755644053d5955c8fd', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', 'user_avatar', NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:19:18', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:19:18', 0);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3Dmlc8DxaZa4Jmkz9fmLyylKq82', 'avatar-1778895201511.png', 'fast-admin/2026/05/16/3Dmlbzd0fAGNaEyK1cImy0uZZEW.png', 'https://oss.yuxuan66.com/fast-admin/2026/05/16/3Dmlbzd0fAGNaEyK1cImy0uZZEW.png', 224675, 'image/png', 'png', '0618c3fc50bbe8f45d8a7dc8e76e04ad15bce16c5db812a2a674fe6dc48550b0', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', 'user_avatar', NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:33:22', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:33:22', 0);
INSERT INTO `sys_file` (`id`, `original_name`, `storage_key`, `url`, `size`, `content_type`, `ext`, `hash`, `storage_type`, `config_id`, `biz_type`, `biz_id`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3Dmlf9jG4vtjelgOPnT8Ozi9vBW', 'avatar-1778895224130.png', 'fast-admin/2026/05/16/3Dmlf4sSDdMK9Z6iv0i97nJYEzd.png', 'https://oss.yuxuan66.com/fast-admin/2026/05/16/3Dmlf4sSDdMK9Z6iv0i97nJYEzd.png', 224675, 'image/png', 'png', '0618c3fc50bbe8f45d8a7dc8e76e04ad15bce16c5db812a2a674fe6dc48550b0', 'OSS', '3DlT9q0UL5EWYfUY6qB1s1vXZEm', 'user_avatar', NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:33:46', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-16 09:33:46', 0);

--
-- Table structure for table `sys_file_config`
--

DROP TABLE IF EXISTS `sys_file_config`;
CREATE TABLE `sys_file_config` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `name` varchar(64) NOT NULL COMMENT '配置名',
  `type` varchar(16) NOT NULL COMMENT 'LOCAL/OSS/S3/FTP/SFTP',
  `config` json NOT NULL COMMENT '类型相关参数',
  `url_prefix` varchar(255) NOT NULL COMMENT '访问地址前缀（如 https://files.example.com）',
  `is_active` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否激活，全表至多 1 行为 1',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `created_by` varchar(64) DEFAULT NULL,
  `created_id` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `updated_id` varchar(32) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_config_name` (`name`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件存储配置';

--
-- Data for table `sys_file_config`
--

INSERT INTO `sys_file_config` (`id`, `name`, `type`, `config`, `url_prefix`, `is_active`, `remark`, `created_by`, `created_id`, `created_at`, `updated_by`, `updated_id`, `updated_at`, `is_deleted`) VALUES ('3DlT9q0UL5EWYfUY6qB1s1vXZEm', '阿里云OSS', 'OSS', '{"bucket": "yuxuan-data", "passive": true, "basePath": "fast-admin/", "endpoint": "oss-cn-hangzhou.aliyuncs.com", "accessKey": "<ALIYUN_ACCESS_KEY_ID>", "secretKey": "<ALIYUN_ACCESS_KEY_SECRET>"}', 'https://oss.yuxuan66.com', 1, NULL, 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:31:48', 'Sir丶雨轩', '35PaELKCOjq8YdhmuOtQWGPrBJh', '2026-05-15 22:33:41', 0);

--
-- Table structure for table `sys_job`
--

DROP TABLE IF EXISTS `sys_job`;
CREATE TABLE `sys_job` (
  `id` varchar(32) NOT NULL,
  `job_name` varchar(64) NOT NULL COMMENT '任务名称',
  `job_group` varchar(64) DEFAULT 'DEFAULT' COMMENT '任务分组',
  `bean_name` varchar(128) NOT NULL COMMENT '调用的 Spring Bean 名',
  `method_name` varchar(64) DEFAULT 'execute' COMMENT '调用方法名（无参或单 String）',
  `method_params` varchar(512) DEFAULT NULL COMMENT '方法参数（JSON 数组或字符串）',
  `cron_expression` varchar(64) NOT NULL COMMENT 'Cron 表达式',
  `misfire_policy` tinyint(1) DEFAULT '1' COMMENT '错过策略: 1立即执行 2忽略 3触发一次',
  `concurrent` tinyint(1) DEFAULT '0' COMMENT '是否允许并发: 1是 0否',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态: 1正常 0暂停',
  `remark` varchar(255) DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `created_id` varchar(32) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `updated_id` varchar(32) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_job_name` (`job_name`,`job_group`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务';

--
-- Data for table `sys_job`
--


--
-- Table structure for table `sys_job_log`
--

DROP TABLE IF EXISTS `sys_job_log`;
CREATE TABLE `sys_job_log` (
  `id` varchar(32) NOT NULL,
  `job_id` varchar(32) NOT NULL COMMENT '任务ID',
  `job_name` varchar(64) NOT NULL,
  `job_group` varchar(64) DEFAULT NULL,
  `bean_name` varchar(128) DEFAULT NULL,
  `method_name` varchar(64) DEFAULT NULL,
  `method_params` varchar(512) DEFAULT NULL,
  `status` tinyint(1) DEFAULT '1' COMMENT '1成功 0失败',
  `cost_time` bigint(20) DEFAULT NULL COMMENT '耗时(ms)',
  `error_msg` text,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_job` (`job_id`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='定时任务执行日志';

--
-- Data for table `sys_job_log`
--


--
-- Table structure for table `sys_login_log`
--

DROP TABLE IF EXISTS `sys_login_log`;
CREATE TABLE `sys_login_log` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(64) DEFAULT NULL COMMENT '用户名',
  `ip` varchar(64) DEFAULT NULL COMMENT 'IP',
  `location` varchar(128) DEFAULT NULL COMMENT '地点',
  `browser` varchar(64) DEFAULT NULL COMMENT '浏览器',
  `os` varchar(64) DEFAULT NULL COMMENT '操作系统',
  `device` varchar(64) DEFAULT NULL COMMENT '设备类型',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：1成功 0失败',
  `msg` varchar(255) DEFAULT NULL COMMENT '描述/失败原因',
  `type` varchar(16) DEFAULT 'LOGIN' COMMENT 'LOGIN/LOGOUT',
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志';

--
-- Data for table `sys_login_log`
--

INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DmrL02JFGhJd4UQ9mh8D0rEiyd', '35PaELKCOjq8YdhmuOtQWGPrBJh', 'yuxuan', 'unknown', NULL, 'Other', 'Other', 'PC', 1, '登录成功', 'LOGIN', '2026-05-16 10:20:25');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DmrQrB5GU6li7K6nvPzQFFP9dS', '35PaELKCOjq8YdhmuOtQWGPrBJh', 'yuxuan', 'unknown', NULL, 'Other', 'Other', 'PC', 1, '登录成功', 'LOGIN', '2026-05-16 10:21:13');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DmsGXZCFnGhMvNbE0jXPRoiJYU', '35PaELKCOjq8YdhmuOtQWGPrBJh', 'yuxuan', '127.0.0.1', NULL, 'Chrome', 'macOS', 'PC', 1, '登录成功', 'LOGIN', '2026-05-16 10:28:04');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DverdixFzjuohJzpmnyZUONbkq', NULL, 'admin', '127.0.0.1', NULL, 'Other', 'Other', 'PC', 0, '用户名或密码错误', 'LOGIN', '2026-05-19 13:06:11');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3Dvewkh1szl1GsqY1Pkgy3avDKI', '35PaELKCOjq8YdhmuOtQWGPrBJh', 'yuxuan', '127.0.0.1', NULL, 'Chrome', 'macOS', 'PC', 1, '登录成功', 'LOGIN', '2026-05-19 13:06:50');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DvfnTKKfxdixD0D5CGaPza0YLv', NULL, 'admin', '127.0.0.1', NULL, 'Other', 'Other', 'PC', 0, '用户名或密码错误', 'LOGIN', '2026-05-19 13:13:51');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DvgHgEfR9sQpSUNPRVjgkDNwFz', NULL, 'admin', '127.0.0.1', NULL, 'Other', 'Other', 'PC', 0, '用户名或密码错误', 'LOGIN', '2026-05-19 13:17:51');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DvgHgvplY6IX4c1RgU1F0e4du9', NULL, 'nonexistent', '127.0.0.1', NULL, 'Other', 'Other', 'PC', 0, '用户名或密码错误', 'LOGIN', '2026-05-19 13:17:51');
INSERT INTO `sys_login_log` (`id`, `user_id`, `username`, `ip`, `location`, `browser`, `os`, `device`, `status`, `msg`, `type`, `created_at`) VALUES ('3DvgHuKcY1obsi1nJNpQMGR9Txy', NULL, 'admin', '127.0.0.1', NULL, 'Other', 'Other', 'PC', 0, '用户名或密码错误', 'LOGIN', '2026-05-19 13:17:52');

--
-- Table structure for table `sys_menu`
--

DROP TABLE IF EXISTS `sys_menu`;
CREATE TABLE `sys_menu` (
  `id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID（KSUID）',
  `pid` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '父菜单ID，顶级菜单为NULL',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '菜单/按钮名称',
  `code` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '菜单/按钮编码，用于权限控制',
  `type` tinyint(4) NOT NULL COMMENT '菜单类型：1=menu, 2=catalog, 3=button, 4=embedded, 5=link',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1启用，0禁用',
  `path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '前端路由路径',
  `active_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '激活路径',
  `component` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '前端组件路径',
  `icon` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '菜单/按钮图标',
  `meta_active_icon` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '激活状态图标',
  `meta_title` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '前端显示标题，可用于国际化',
  `meta_order` int(11) DEFAULT '0' COMMENT '菜单排序，数值越小越靠前',
  `meta_affix_tab` tinyint(1) DEFAULT '0' COMMENT '是否固定标签页',
  `meta_keep_alive` tinyint(1) DEFAULT '0' COMMENT '是否保持组件活跃状态',
  `meta_hide_in_menu` tinyint(1) DEFAULT '0' COMMENT '是否在菜单中隐藏',
  `meta_hide_children_in_menu` tinyint(1) DEFAULT '0' COMMENT '是否隐藏子菜单',
  `meta_hide_in_breadcrumb` tinyint(1) DEFAULT '0' COMMENT '是否在面包屑中隐藏',
  `meta_hide_in_tab` tinyint(1) DEFAULT '0' COMMENT '是否在标签页中隐藏',
  `meta_badge` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '徽标显示内容',
  `meta_badge_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '徽标类型，如 normal/dot',
  `meta_badge_variants` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '徽标颜色或样式',
  `meta_iframe_src` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内嵌 IFrame 链接',
  `meta_link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '外部链接地址',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `created_by` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人名字',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `updated_by` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人名字',
  `updated_at` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  `created_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `updated_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记：false=未删除，true=已删除',
  PRIMARY KEY (`id`),
  KEY `idx_sys_menu_pid` (`pid`),
  KEY `idx_sys_menu_type` (`type`),
  KEY `idx_sys_menu_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统菜单表（支持多级菜单和按钮权限）';

--
-- Data for table `sys_menu`
--

INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('03a5e92d0929456796f1e06651f', 'sys_job_menu', 'SysJobEdit', 'system:job:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysJobEdit', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:45:09.156892', NULL, '2026-05-16 10:45:09.390322', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('1671612b50b414ae76ed2935del', '35fcfg9ef55798c3ca9611a9c14', 'SysFileConfigDelete', 'system:file:config:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, '删除', 2, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('1b3eb8846f65413384429bc181d', 'sys_config_menu', 'SysConfigDel', 'system:config:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysConfigDel', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.120004', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('20dec697ac954fb79364a7d3f2d', 'sys_job_menu', 'SysJobDel', 'system:job:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysJobDel', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:45:09.156892', NULL, '2026-05-16 10:45:09.457640', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('3122e315d4ecf6d5c2f0ed35add', '35fcfg9ef55798c3ca9611a9c14', 'SysFileConfigAdd', 'system:file:config:add', 3, 1, NULL, NULL, NULL, NULL, NULL, '新增', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35akSVTGkD6d2WkjR0LUue4Rg1H', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SysUser', 'system:user:list', 1, 1, '/system/user', NULL, '/system/user/list', 'carbon:user', NULL, '用户管理', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Sir丶雨轩', '2025-11-17 12:59:29.579000', 'Sir丶雨轩', '2025-11-17 12:59:29.580000', '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh', 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35aN4sLcP2Gd9PDUhNqmImfscW0', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SysRole', 'system:role:list', 1, 1, '/system/role', NULL, '/system/role/list', 'carbon:user-military', NULL, '角色管理', 0, 0, 0, 0, 0, 0, 0, '', 'normal', 'warning', NULL, NULL, NULL, '系统管理员', '2025-11-17 09:47:14.240000', '系统管理员', '2025-11-17 09:47:14.251000', '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh', 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35aNAOJVk7dc8Cstw9k6xee1SnN', '35aN4sLcP2Gd9PDUhNqmImfscW0', 'SysRoleAdd', 'system:role:add', 3, 1, '', NULL, NULL, NULL, NULL, '新增', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '系统管理员', '2025-11-17 09:47:58.986000', '系统管理员', '2025-11-17 09:47:58.989000', '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh', 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35aNDFxbMYFIkujj27AXDTmSgH7', '35aN4sLcP2Gd9PDUhNqmImfscW0', 'SysRoleEdit', 'system:role:edit', 3, 1, '', NULL, NULL, NULL, NULL, '编辑', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '系统管理员', '2025-11-17 09:48:20.231000', '系统管理员', '2025-11-17 09:48:20.233000', '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh', 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35aNG4IapjYOpcanRPKLpw77jwX', '35aN4sLcP2Gd9PDUhNqmImfscW0', 'SysRoleDel', 'system:role:del', 3, 1, '', NULL, NULL, NULL, NULL, '删除', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, '系统管理员', '2025-11-17 09:48:43.126000', '系统管理员', '2025-11-17 09:48:43.129000', '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh', 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35dGLGC3ElMgYMHULp3DQbzcdfn', '35PlZt0sYaZm7yBghgvZHyDlQ8R', 'SysDeptList', 'system:dept:list', 3, 1, '', NULL, NULL, NULL, NULL, '查看', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, 'Sir丶雨轩', '2025-11-18 10:21:17.214000', 'Sir丶雨轩', '2025-11-18 10:24:13.839000', '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh', 1);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35fcfg9ef55798c3ca9611a9c14', '35fmgr7c8366ccdcc31f6ab5de7', 'SysFileConfig', 'system:file:config:list', 1, 1, '/system/file-config', NULL, '/system/file-config/list', 'carbon:cloud-upload', NULL, '文件配置', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:07:33.886573', NULL, '2026-05-15 22:28:16.543026', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35flstd84b75d35ae70afd0a236', '35fmgr7c8366ccdcc31f6ab5de7', 'SysFile', 'system:file:list', 1, 1, '/system/file', NULL, '/system/file/list', 'carbon:document', NULL, '文件列表', 1, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:07:33.886573', NULL, '2026-05-15 22:28:16.618596', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35fmgr7c8366ccdcc31f6ab5de7', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'FileManage', NULL, 2, 1, '/system/file-manage', NULL, NULL, 'carbon:folder', NULL, '文件管理', 12, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:28:15.544721', NULL, '2026-05-15 22:28:15.544721', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZm6yfj0946lcdUPH1bWe1Za', '35PlZt0sYaZm7yBghgvZHyDlQ8R', 'SystemDeptCreate', 'system:dept:add', 3, 1, NULL, NULL, NULL, NULL, NULL, '新增', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '创建部门按钮', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:07:01.845283', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZml410bKeFH9y1MGrV5lfEL', '35PlZt0sYaZm7yBghgvZHyDlQ8R', 'SystemDeptDelete', 'system:dept:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, '删除', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '删除部门按钮', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:07:08.807869', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZmoOOFFC7MbxfHKRSm37iS6', '35PlZrV4t4FP7RmvAjH2hHxslTu', 'SystemMenuCreate', 'system:menu:add', 3, 1, NULL, NULL, NULL, NULL, NULL, '新增', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '创建菜单按钮', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:03:01.289789', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZmvi8gW3sDhyVIA8oe8YMLG', NULL, 'Workspace', NULL, 1, 1, '/workspace', NULL, '/dashboard/workspace/index', 'carbon:workspace', NULL, '工作台', 0, 1, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '工作台菜单', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-13 15:41:56.489829', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZn0U8GQDyiNQwKvbe2Q2wJk', '35PlZrV4t4FP7RmvAjH2hHxslTu', 'SystemMenuDelete', 'system:menu:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, '删除', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '删除菜单按钮', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 15:47:46.965411', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZqPBF9fiZmsewd7xsKC9kB1', '35PlZt0sYaZm7yBghgvZHyDlQ8R', 'SystemDeptEdit', 'system:dept:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, '编辑', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '编辑部门按钮', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:07:16.157794', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZraW752xuXEuWlTXKDCXVD1', '35PlZrV4t4FP7RmvAjH2hHxslTu', 'SystemMenuEdit', 'system:menu:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, '编辑', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '编辑菜单按钮', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:03:06.888146', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZrV4t4FP7RmvAjH2hHxslTu', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SystemMenu', 'system:menu:list', 1, 1, '/system/menu', NULL, '/system/menu/list', 'carbon:menu', NULL, '菜单管理', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '菜单管理', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:07:26.968823', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZt0sYaZm7yBghgvZHyDlQ8R', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SystemDept', '', 1, 1, '/system/dept', NULL, '/system/dept/list', 'carbon:container-services', NULL, '部门管理', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, '部门管理', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-14 16:07:20.933952', NULL, '35PaELKCOjq8YdhmuOtQWGPrBJh', 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('35PlZtb7CCmpEZ5XWwTZqEX7fMZ', NULL, 'System', NULL, 2, 1, '/system', NULL, NULL, 'carbon:settings', NULL, '系统管理', 9997, 0, 0, 0, 0, 0, 0, '', '', '', NULL, NULL, '系统管理目录', 'system', '2025-11-13 15:41:56.489829', 'system', '2025-11-13 15:41:56.489829', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('4d8d3c3af4a945de80f241a181c', 'sys_dict_menu', 'SysDictDataEdit', 'system:dict:data:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysDictDataEdit', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.841528', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('56e811b5628643e3b88aee98b33', 'sys_dict_menu', 'SysDictTypeDel', 'system:dict:type:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysDictTypeDel', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.400691', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('5b8f5eef71bb423d81d3b01d3f0', 'sys_dict_menu', 'SysDictTypeEdit', 'system:dict:type:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysDictTypeEdit', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.330760', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('871bdf0bd7054b2a8e83cc1ce3c', 'sys_config_menu', 'SysConfigEdit', 'system:config:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysConfigEdit', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.050276', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('871e5be9fe6e431eb105e467ceb', 'sys_dict_menu', 'SysDictDataAdd', 'system:dict:data:add', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysDictDataAdd', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.771496', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('a04831863f234156ae1cc6cd706', 'sys_job_menu', 'SysJobAdd', 'system:job:add', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysJobAdd', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:45:09.156892', NULL, '2026-05-16 10:45:09.323037', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('b271e8f9d6c64d8a980bceb44ef', 'sys_login_log', 'SysLoginLogDelete', 'system:log:login:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysLoginLogDelete', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.814039', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('c29db81ccafd49c3ac3e990ca1c', 'sys_online_menu', 'SysOnlineKickout', 'system:online:kickout', 3, 1, NULL, NULL, NULL, NULL, NULL, '强制下线', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 20:55:40.482144', NULL, '2026-05-16 20:55:40.655918', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('c7086c22b7bd6706c8c25435upl', '35flstd84b75d35ae70afd0a236', 'SysFileUpload', 'system:file:upload', 3, 1, NULL, NULL, NULL, NULL, NULL, '上传', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('d206c1ee8dc24ba1ae2873ef0af', 'sys_op_log', 'SysOperationLogDelete', 'system:log:operation:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysOperationLogDelete', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.667679', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('d64c72cc8cce4c57a34e58d2a54', 'sys_config_menu', 'SysConfigAdd', 'system:config:add', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysConfigAdd', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.954824', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('e3651e7cf7382d4202b5c035edt', '35fcfg9ef55798c3ca9611a9c14', 'SysFileConfigEdit', 'system:file:config:edit', 3, 1, NULL, NULL, NULL, NULL, NULL, '编辑', 1, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('f0d731c8f0c54ce7b183d13e309', 'sys_dict_menu', 'SysDictTypeAdd', 'system:dict:type:add', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysDictTypeAdd', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.260399', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('f1bb21997562811b8dbcd135dwn', '35flstd84b75d35ae70afd0a236', 'SysFileDownload', 'system:file:download', 3, 1, NULL, NULL, NULL, NULL, NULL, '下载', 1, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('fccb25f29043e633715c8935fdl', '35flstd84b75d35ae70afd0a236', 'SysFileDelete', 'system:file:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, '删除', 2, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('fd3c5aa8b46940e6ad4c11ad873', 'sys_dict_menu', 'SysDictDataDel', 'system:dict:data:delete', 3, 1, NULL, NULL, NULL, NULL, NULL, 'SysDictDataDel', 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.911008', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('ff6aa327abf9329be65edb35act', '35fcfg9ef55798c3ca9611a9c14', 'SysFileConfigActivate', 'system:file:config:activate', 3, 1, NULL, NULL, NULL, NULL, NULL, '激活', 3, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-15 22:19:11.748346', NULL, '2026-05-15 22:19:11.748346', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_config_menu', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SysConfig', 'system:config:list', 1, 1, '/system/config', NULL, 'system/config/list', 'lucide:sliders', NULL, '系统参数', 60, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.884507', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_dict_menu', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SysDict', 'system:dict:list', 1, 1, '/system/dict', NULL, 'system/dict/list', 'lucide:book-marked', NULL, '数据字典', 70, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:01.190405', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_job_log_menu', 'sys_monitor', 'SysJobLog', 'system:job:log:list', 1, 1, '/system/job/log', NULL, 'system/job/log/list', 'lucide:scroll-text', NULL, '任务日志', 31, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:45:09.156892', NULL, '2026-05-16 10:45:09.577258', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_job_menu', 'sys_monitor', 'SysJob', 'system:job:list', 1, 1, '/system/job', NULL, 'system/job/list', 'lucide:timer', NULL, '定时任务', 30, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:45:09.156892', NULL, '2026-05-16 10:45:09.254377', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_login_log', 'sys_monitor', 'SysLoginLog', 'system:log:login:list', 1, 1, '/system/log/login', NULL, 'system/log/login/list', 'lucide:log-in', NULL, '登录日志', 20, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.738623', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_monitor', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ', 'SysMonitor', NULL, 2, 1, '/system/monitor', NULL, NULL, 'lucide:activity', NULL, '系统监控', 50, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.525766', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_online_menu', 'sys_monitor', 'SysOnline', 'system:online:list', 1, 1, '/system/monitor/online', NULL, 'system/monitor/online/index', 'lucide:users-round', NULL, '在线用户', 45, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 20:55:40.482144', NULL, '2026-05-16 20:55:40.583180', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_op_log', 'sys_monitor', 'SysOperationLog', 'system:log:operation:list', 1, 1, '/system/log/operation', NULL, 'system/log/operation/list', 'lucide:scroll-text', NULL, '操作日志', 10, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 10:07:00.431864', NULL, '2026-05-16 10:07:00.597420', NULL, NULL, 0);
INSERT INTO `sys_menu` (`id`, `pid`, `name`, `code`, `type`, `status`, `path`, `active_path`, `component`, `icon`, `meta_active_icon`, `meta_title`, `meta_order`, `meta_affix_tab`, `meta_keep_alive`, `meta_hide_in_menu`, `meta_hide_children_in_menu`, `meta_hide_in_breadcrumb`, `meta_hide_in_tab`, `meta_badge`, `meta_badge_type`, `meta_badge_variants`, `meta_iframe_src`, `meta_link`, `remark`, `created_by`, `created_at`, `updated_by`, `updated_at`, `created_id`, `updated_id`, `is_deleted`) VALUES ('sys_server_monitor', 'sys_monitor', 'SysServerMonitor', 'system:monitor:server', 1, 1, '/system/monitor/server', NULL, 'system/monitor/server/index', 'lucide:gauge', NULL, '服务监控', 40, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-16 15:22:10.033120', NULL, '2026-05-16 15:22:10.113167', NULL, NULL, 0);

--
-- Table structure for table `sys_operation_log`
--

DROP TABLE IF EXISTS `sys_operation_log`;
CREATE TABLE `sys_operation_log` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `title` varchar(128) DEFAULT NULL COMMENT '操作模块/标题',
  `business_type` varchar(32) DEFAULT NULL COMMENT '业务类型：CREATE/UPDATE/DELETE/QUERY/IMPORT/EXPORT/OTHER',
  `method` varchar(255) DEFAULT NULL COMMENT '方法名 ClassName.methodName',
  `request_method` varchar(16) DEFAULT NULL COMMENT 'HTTP 请求方式',
  `operator_type` varchar(16) DEFAULT NULL COMMENT '操作类别 ADMIN/USER',
  `user_id` varchar(32) DEFAULT NULL COMMENT '用户ID',
  `username` varchar(64) DEFAULT NULL COMMENT '用户名',
  `url` varchar(500) DEFAULT NULL COMMENT '请求URL',
  `ip` varchar(64) DEFAULT NULL COMMENT '操作 IP',
  `location` varchar(128) DEFAULT NULL COMMENT '操作地点',
  `request_params` text COMMENT '请求参数 JSON',
  `response_result` text COMMENT '响应结果 JSON',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：1成功 0失败',
  `error_msg` text COMMENT '错误消息',
  `cost_time` bigint(20) DEFAULT NULL COMMENT '耗时(ms)',
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_created` (`created_at`),
  KEY `idx_business` (`business_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志';

--
-- Data for table `sys_operation_log`
--


--
-- Table structure for table `sys_role`
--

DROP TABLE IF EXISTS `sys_role`;
CREATE TABLE `sys_role` (
  `id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID（KSUID）',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '角色名字',
  `code` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '角色编码',
  `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '角色备注',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否启用',
  `created_by` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `updated_by` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记：false未删除，true已删除',
  `created_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `updated_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_code` (`code`) COMMENT '角色编码唯一'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统角色表';

--
-- Data for table `sys_role`
--

INSERT INTO `sys_role` (`id`, `name`, `code`, `remark`, `is_enabled`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35azimPyC4hvuQhUjgxpPqAHaYR', '测试', 'ROLE_测试', NULL, 1, 'Sir丶雨轩', '2025-11-17 15:04:59.016000', 'Sir丶雨轩', '2025-11-18 10:25:07.780000', 1, '35PaELKCOjq8YdhmuOtQWGPrBJh', '35PaELKCOjq8YdhmuOtQWGPrBJh');
INSERT INTO `sys_role` (`id`, `name`, `code`, `remark`, `is_enabled`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '系统管理员', 'System', '系统级管理员，拥有最高权限', 1, NULL, '2025-11-13 15:39:55.905897', '系统管理员', '2025-11-13 15:39:55.905897', 0, NULL, '35PaELKCOjq8YdhmuOtQWGPrBJh');

--
-- Table structure for table `sys_roles_menus`
--

DROP TABLE IF EXISTS `sys_roles_menus`;
CREATE TABLE `sys_roles_menus` (
  `role_id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '角色ID（KSUID）',
  `menu_id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '菜单ID（KSUID）',
  PRIMARY KEY (`role_id`,`menu_id`),
  KEY `idx_roles_menus_role` (`role_id`),
  KEY `idx_roles_menus_menu` (`menu_id`),
  CONSTRAINT `sys_roles_menus_ibfk_1` FOREIGN KEY (`menu_id`) REFERENCES `sys_menu` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sys_roles_menus_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `sys_role` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色菜单关联表';

--
-- Data for table `sys_roles_menus`
--

INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '03a5e92d0929456796f1e06651f');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '1671612b50b414ae76ed2935del');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '1b3eb8846f65413384429bc181d');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '20dec697ac954fb79364a7d3f2d');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '3122e315d4ecf6d5c2f0ed35add');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35akSVTGkD6d2WkjR0LUue4Rg1H');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35aN4sLcP2Gd9PDUhNqmImfscW0');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35aNAOJVk7dc8Cstw9k6xee1SnN');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35aNDFxbMYFIkujj27AXDTmSgH7');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35aNG4IapjYOpcanRPKLpw77jwX');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35fcfg9ef55798c3ca9611a9c14');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35flstd84b75d35ae70afd0a236');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35fmgr7c8366ccdcc31f6ab5de7');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZm6yfj0946lcdUPH1bWe1Za');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZml410bKeFH9y1MGrV5lfEL');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZmoOOFFC7MbxfHKRSm37iS6');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZmvi8gW3sDhyVIA8oe8YMLG');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZn0U8GQDyiNQwKvbe2Q2wJk');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZqPBF9fiZmsewd7xsKC9kB1');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZraW752xuXEuWlTXKDCXVD1');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZrV4t4FP7RmvAjH2hHxslTu');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZt0sYaZm7yBghgvZHyDlQ8R');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '35PlZtb7CCmpEZ5XWwTZqEX7fMZ');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '4d8d3c3af4a945de80f241a181c');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '56e811b5628643e3b88aee98b33');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '5b8f5eef71bb423d81d3b01d3f0');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '871bdf0bd7054b2a8e83cc1ce3c');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', '871e5be9fe6e431eb105e467ceb');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'a04831863f234156ae1cc6cd706');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'b271e8f9d6c64d8a980bceb44ef');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'c29db81ccafd49c3ac3e990ca1c');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'c7086c22b7bd6706c8c25435upl');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'd206c1ee8dc24ba1ae2873ef0af');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'd64c72cc8cce4c57a34e58d2a54');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'e3651e7cf7382d4202b5c035edt');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'f0d731c8f0c54ce7b183d13e309');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'f1bb21997562811b8dbcd135dwn');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'fccb25f29043e633715c8935fdl');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'fd3c5aa8b46940e6ad4c11ad873');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'ff6aa327abf9329be65edb35act');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_config_menu');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_dict_menu');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_job_log_menu');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_job_menu');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_login_log');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_monitor');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_online_menu');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_op_log');
INSERT INTO `sys_roles_menus` (`role_id`, `menu_id`) VALUES ('35PlNb9zFOIQVWx8YoSlGGxjhHF', 'sys_server_monitor');

--
-- Table structure for table `sys_user`
--

DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user` (
  `id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID（KSUID）',
  `dept_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '部门ID',
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户名',
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '密码（加密存储）',
  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '邮箱',
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机号',
  `nickname` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '昵称',
  `avatar` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像URL',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '状态：0正常，1冻结，2锁定',
  `sex` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别：1男，2女，0未知',
  `login_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最后登录IP（支持IPv6）',
  `login_city` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最后登录城市',
  `login_time` timestamp(6) NULL DEFAULT NULL COMMENT '最后登录时间',
  `created_by` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间',
  `updated_by` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '更新时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记：false未删除，true已删除',
  `created_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人ID',
  `updated_id` varchar(27) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_username` (`username`) COMMENT '用户名唯一',
  KEY `idx_user_status` (`status`),
  KEY `idx_user_phone` (`phone`),
  KEY `idx_user_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统用户表';

--
-- Data for table `sys_user`
--

INSERT INTO `sys_user` (`id`, `dept_id`, `username`, `password`, `email`, `phone`, `nickname`, `avatar`, `status`, `sex`, `login_ip`, `login_city`, `login_time`, `created_by`, `created_at`, `updated_by`, `updated_at`, `is_deleted`, `created_id`, `updated_id`) VALUES ('35PaELKCOjq8YdhmuOtQWGPrBJh', '35SZAmUMGKqvpWTC2EQODUKm59T', 'yuxuan', '$2a$10$U8T8RweTxtj/Qy.laTxc/evrC.esn6O4CKtRnI9SSFj88GsQxgr5m', 'dev@oofo.cc', '15715312568', 'Sir丶雨轩', 'https://oss.yuxuan66.com/fast-admin/2026/05/16/3Dmlf4sSDdMK9Z6iv0i97nJYEzd.png', 0, 1, NULL, NULL, NULL, NULL, '2025-11-13 14:08:04.283450', 'Sir丶雨轩', '2025-11-18 11:23:01.427000', 0, NULL, '35PaELKCOjq8YdhmuOtQWGPrBJh');

--
-- Table structure for table `sys_users_roles`
--

DROP TABLE IF EXISTS `sys_users_roles`;
CREATE TABLE `sys_users_roles` (
  `user_id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户ID（KSUID）',
  `role_id` varchar(27) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '角色ID（KSUID）',
  PRIMARY KEY (`user_id`,`role_id`),
  KEY `idx_users_roles_user` (`user_id`),
  KEY `idx_users_roles_role` (`role_id`),
  CONSTRAINT `sys_users_roles_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `sys_role` (`id`) ON DELETE CASCADE,
  CONSTRAINT `sys_users_roles_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户角色关联表';

--
-- Data for table `sys_users_roles`
--

INSERT INTO `sys_users_roles` (`user_id`, `role_id`) VALUES ('35PaELKCOjq8YdhmuOtQWGPrBJh', '35PlNb9zFOIQVWx8YoSlGGxjhHF');

SET FOREIGN_KEY_CHECKS=1;
